package com.example.MovieExam.DAL.DataAccess;

import com.example.MovieExam.BE.Category;
import com.example.MovieExam.DAL.DB.DBConnector;
import com.example.MovieExam.DAL.Interfaces.ICategoryDA;

import java.io.IOException;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class CategoriesDAO implements ICategoryDA {
    @Override
    public List<Category> getAllCategories() throws Exception {
        ArrayList<Category> allCategories = new ArrayList<>();

        //try with resources
        try (Connection conn = new DBConnector().getConnection();
             Statement stmt = conn.createStatement()) {

            String sql = "SELECT * FROM dbo.Category;";
            ResultSet rs = stmt.executeQuery(sql);

            //Loop through rows from the database result set
            while (rs.next()) {

                //map DB row to Category object
                int id = rs.getInt("Id");
                String name = rs.getString("Name");

                Category category = new Category(id, name);
                allCategories.add(category);
            }
            return allCategories;

        } catch (SQLException ex) {
            ex.printStackTrace();
            throw new Exception("Could not get categories from database", ex);
        }
    }

    @Override
    public Category createCategory(Category newCategory) throws Exception {

        String sql = "INSERT INTO dbo.Category (Name) VALUES ('" + Category.getName() + "'," + ");";

        System.out.println(sql);

        try (Connection conn = DBConnector.getConnection()) {

            Statement stmt = conn.createStatement();

            // Run the specified SQL statement
            stmt.execute(sql, Statement.RETURN_GENERATED_KEYS); // sql injection risk

            // Get the generated ID from the DB
            ResultSet rs = stmt.getGeneratedKeys();
            int id = 0;

            if (rs.next()) {
                id = rs.getInt(1);
            }

            // Create category object and send up the layers
            // We need the ID generated by the DB in the GUI
            Category createdCategory = new Category(id, Category.getName());

            return createdCategory;
        } catch (SQLException ex) {
            ex.printStackTrace();
            throw new Exception("Could not create category", ex);
        }
    }

    @Override
    public void updateCategory(Category category) throws Exception {
        String sql = "UPDATE dbo.Category SET Name = ?, WHERE ID = ?";

        try (Connection conn = DBConnector.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            // Bind parameters
            stmt.setString(1, category.getName());
            stmt.setInt(3, category.getId());

            // Run the specified SQL statement
            stmt.executeUpdate();
        } catch (SQLException ex) {
            // fixme: optionally log to file, db etc.
            throw new Exception("Could not get categories from database.", ex);
        }
    }

    @Override
    public void deleteCategory(Category category) throws Exception {

        String sql = "DELETE FROM dbo.Movie WHERE ID = ?;";

        try (Connection conn = DBConnector.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            // Bind parameters
            stmt.setInt(1, category.getId());

            // Run the specified SQL statement
            stmt.executeUpdate();
        } catch (SQLException ex) {
            // fixme: optionally log to file, db etc.
            throw new Exception("Could not get movies from database.", ex);
        }
    }
}
